import { Save } from "lucide-react";

type Category = { id: string; nameZh: string; nameEn: string | null };
type Value = { categoryId: string; model: string; slug: string; nameZh: string; nameEn: string; taglineZh: string; taglineEn: string; skus: string[]; tags: string[] };

export function ProductForm({ categories, value, action, submitLabel = "保存产品" }: { categories: Category[]; value?: Value; action: (formData: FormData) => void | Promise<void>; submitLabel?: string }) {
  return <form action={action} className="settings-form product-form"><section className="form-card"><div className="form-card-title"><div><h2>基础与分类</h2><p>型号在企业内唯一；URL 别名只允许小写字母、数字和连字符。</p></div><span>01</span></div><div className="form-grid"><label>产品分类<select name="categoryId" defaultValue={value?.categoryId} required><option value="">选择分类</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.nameZh} / {item.nameEn}</option>)}</select></label><label>产品型号<input name="model" defaultValue={value?.model} placeholder="例如 XW30" required/></label><label className="wide">URL 别名<input name="slug" defaultValue={value?.slug} placeholder="例如 xw30-linear-wall-washer" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label className="wide">产品标签<input name="tags" defaultValue={value?.tags.join("，")} placeholder="逗号分隔，例如 户外，洗墙，IP65（最多 10 个）"/></label></div></section>
    <section className="form-card bilingual-card"><div className="form-card-title"><div><h2>中英文内容</h2><p>两种语言独立保存和发布，不互相冒充翻译。</p></div><span>02</span></div><div className="language-columns"><div><p>简体中文 <em>ZH-CN</em></p><label>产品名称<input name="nameZh" defaultValue={value?.nameZh} required/></label><label>一句话卖点<textarea name="taglineZh" rows={3} defaultValue={value?.taglineZh}/></label></div><div><p>English <em>EN</em></p><label>Product name<input name="nameEn" defaultValue={value?.nameEn} required/></label><label>Tagline<textarea name="taglineEn" rows={3} defaultValue={value?.taglineEn}/></label></div></div></section>
    <section className="form-card"><div className="form-card-title"><div><h2>规格 / SKU</h2><p>每行填写一个 SKU。保存时会按当前内容重建规格列表。</p></div><span>03</span></div><label className="sku-field">SKU 列表<textarea name="skus" rows={7} defaultValue={value?.skus.join("\n")} placeholder={'XW30-18W\nXW30-24W\nXW30-36W'} required/><small>支持换行或英文逗号分隔，最多 30 个。</small></label></section>
    <div className="sticky-save"><p>新产品默认保存为草稿，拥有发布权限的编辑可随后直接发布。</p><button><Save/>{submitLabel}</button></div>
  </form>;
}
