import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Download, FileText, Images, Layers3, Ruler, Send, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { getDb } from "@/lib/db";
import { getPublicTenant, isSiteLocale, localeToDb } from "@/lib/public-site";
import { alternatesFor, siteBaseUrl } from "@/lib/seo";
import { createInquiryAction } from "../../contact/actions";
import { splitPublicAssets } from "@/lib/asset-roles";
import { ProductGallery } from "./product-gallery";

function raw(value: unknown) { return typeof value === "object" && value !== null && "raw" in value ? String((value as {raw:unknown}).raw) : "—"; }

export async function generateMetadata({ params }: PageProps<"/[locale]/products/[slug]">): Promise<Metadata> { const { locale, slug } = await params; if (!isSiteLocale(locale)) return {}; const tenant = await getPublicTenant(); const tr = await getDb().productTranslation.findFirst({ where: { locale: localeToDb[locale], isPublished: true, product: { tenantId: tenant.id, slug, status: "PUBLISHED", deletedAt: null } } }); if (!tr) notFound(); return { metadataBase: await siteBaseUrl(), title: tr.seoTitle ?? tr.name, description: tr.seoDescription ?? tr.tagline ?? tenant.description ?? undefined, alternates: alternatesFor(locale, `/products/${slug}`) }; }

export default async function ProductDetail({ params, searchParams }: PageProps<"/[locale]/products/[slug]">) {
  const { locale, slug } = await params; if (!isSiteLocale(locale)) notFound(); const { sent, error } = await searchParams; const tenant = await getPublicTenant(); const dbLocale = localeToDb[locale]; const zh = locale === "zh-CN"; const inquire = createInquiryAction.bind(null, locale);
  const product = await getDb().product.findFirst({ where: { tenantId: tenant.id, slug, status: "PUBLISHED", deletedAt: null, translations: { some: { locale: dbLocale, isPublished: true } } }, include: { category: { include: { templates: { orderBy: { version: "desc" }, take: 1, include: { definitions: { where: { isPublic: true }, orderBy: [{ groupName: "asc" }, { sortOrder: "asc" }] } } } } }, translations: { where: { locale: dbLocale, isPublished: true }, take: 1 }, variants: { where: { isActive: true }, orderBy: { sortOrder: "asc" }, include: { values: true } }, assets: { where: { asset: { visibility: "PUBLIC", deletedAt: null } }, include: { asset: true }, orderBy: { sortOrder: "asc" } } } });
  if (!product) notFound(); const tr = product.translations[0]; const definitions = product.category.templates[0]?.definitions ?? []; const { gallery, cadImages, downloads } = splitPublicAssets(product.assets);
  return <main className="public-product"><Link className="product-back" href={`/${locale}/products`}><ArrowLeft/>{zh?"返回产品中心":"Back to products"}</Link><section className="product-hero-real"><div><p>{product.category.nameZh} · {product.model}</p><h1>{tr.name}</h1><span>{tr.tagline}</span><dl><div><dt>{zh?"规格":"Variants"}</dt><dd>{product.variants.length} SKU</dd></div><div><dt>{zh?"公开资料":"Public files"}</dt><dd>{product.assets.length}</dd></div></dl></div><div className="product-light-object"><i/><i/><span>{product.model}</span></div></section>
    {gallery.length > 0 && <section className="product-gallery-section"><div className="spec-heading"><Images/><div><p>PRODUCT GALLERY</p><h2>{zh?"产品图片":"Product images"}</h2></div></div><ProductGallery images={gallery.map(({asset})=>({id:asset.id,src:`/api/assets/${asset.id}`,alt:`${product.model} · ${asset.fileName}`}))}/></section>}
    {cadImages.length > 0 && <section className="cad-section"><div className="spec-heading"><Ruler/><div><p>DIMENSION DRAWINGS</p><h2>{zh?"尺寸图":"Dimension drawings"}</h2></div></div><div className="cad-grid">{cadImages.map(({asset})=><a className="cad-card" href={`/api/assets/${asset.id}`} key={asset.id} target="_blank" rel="noreferrer"><img src={`/api/assets/${asset.id}`} alt={asset.fileName} loading="lazy"/><span>{asset.fileName}</span></a>)}</div></section>}
    <section className="spec-section"><div className="spec-heading"><Layers3/><div><p>STRUCTURED SPECIFICATIONS</p><h2>{zh?"规格与技术参数":"Variants & specifications"}</h2></div></div>{definitions.length ? <div className="public-spec-matrix" style={{"--sku-count":Math.max(product.variants.length,1)} as React.CSSProperties}><div className="spec-row head"><span>{zh?"参数":"Parameter"}</span>{product.variants.map(v=><span key={v.id}>{v.sku}</span>)}</div>{definitions.map(def=><div className="spec-row" key={def.id}><span><b>{zh?def.labelZh:(def.labelEn??def.labelZh)}</b><small>{def.groupName}</small></span>{product.variants.map(v=><span key={v.id}>{raw(v.values.find(x=>x.definitionId===def.id)?.valueJson)} <i>{def.unit}</i></span>)}</div>)}</div> : <p className="no-specs">{zh?"该产品尚无公开参数。":"No public specifications are available."}</p>}</section>
    <section className="download-section"><div className="spec-heading"><Download/><div><p>PUBLIC DOCUMENTS</p><h2>{zh?"公开技术资料":"Public technical files"}</h2></div></div><div className="public-downloads">{downloads.map(({asset,role})=><a href={`/api/assets/${asset.id}`} key={asset.id}><FileText/><div><b>{asset.fileName}</b><small>{role} · {(Number(asset.sizeBytes)/1024/1024).toFixed(2)} MB</small></div><span>{zh?"下载":"Download"}<Download/></span></a>)}{!downloads.length&&<p>{zh?"当前没有公开附件。":"No public files are available."}</p>}</div></section>
    <aside className="fact-note"><ShieldCheck/><p>{zh?"页面仅展示本企业已发布、当前语言可见且明确标记为公开的数据与文件。":"This page only shows published, language-visible data and files explicitly marked public for this company."}</p></aside>
    <section className="public-inquiry"><div className="spec-heading"><Send/><div><p>PRODUCT INQUIRY</p><h2>{zh?"对这个产品感兴趣？":"Interested in this product?"}</h2></div></div>{sent === "1" && <div className="inquiry-success">{zh?"询盘已提交，我们会尽快与你联系。":"Your inquiry has been received. We will contact you shortly."}</div>}{error === "rate_limited" && <div className="form-error">{zh?"提交过于频繁，请一小时后再试。":"Too many submissions. Please try again in an hour."}</div>}{error && error !== "rate_limited" && <div className="form-error">{zh?"请检查必填项和邮箱格式。":"Please check required fields and your email address."}</div>}<form action={inquire} className="inquiry-form"><input className="form-honeypot" name="website" tabIndex={-1} autoComplete="off"/><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="redirect" value={`/${locale}/products/${product.slug}`}/><div className="inquiry-grid"><label>{zh?"姓名 *":"Name *"}<input name="name" required/></label><label>{zh?"邮箱 *":"Email *"}<input name="email" type="email" required/></label><label>{zh?"公司":"Company"}<input name="company"/></label><label className="wide">{zh?"项目需求 *":"Project requirements *"}<textarea name="message" rows={5} required minLength={10} defaultValue={zh?`我对 ${product.model} 感兴趣，请提供更多选型信息。`:`I'm interested in ${product.model}. Please provide more selection information.`}/></label></div><button><span>{zh?"提交产品询盘":"Send product inquiry"}</span><Send/></button></form></section>
  </main>;
}
