import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth/dal";
import { getDb } from "@/lib/db";
import { AdminPage } from "../../components/admin-page";
import { ConfirmForm } from "../../components/confirm-form";
import { deleteProjectAction, setProjectStatusAction, updateProjectAction } from "../actions";
import { ProjectForm } from "../project-form";

export default async function EditProjectPage({ params, searchParams }: { params:Promise<{id:string}>; searchParams:Promise<{saved?:string;created?:string;error?:string}> }) { const session = await requirePermission("content:write"); const {id}=await params; const state=await searchParams; const [item, products] = await Promise.all([getDb().projectCase.findFirst({where:{id,tenantId:session.tenantId,deletedAt:null},include:{translations:true,products:{select:{productId:true}}}}), getDb().product.findMany({ where: { tenantId: session.tenantId, deletedAt: null }, orderBy: { updatedAt: "desc" }, select: { id: true, model: true, translations: { where: { locale: "ZH_CN" }, take: 1, select: { name: true } } } })]); if(!item)notFound(); const zh=item.translations.find(t=>t.locale==="ZH_CN"); const en=item.translations.find(t=>t.locale==="EN"); const update=updateProjectAction.bind(null,id); const zhAction=setProjectStatusAction.bind(null,id,"ZH_CN",!zh?.isPublished); const enAction=setProjectStatusAction.bind(null,id,"EN",!en?.isPublished); const remove=deleteProjectAction.bind(null,id); const actions=<div className="locale-publish-actions"><form action={zhAction}><button className={zh?.isPublished?"is-live":""}><b>中文</b><span>{zh?.isPublished?"已上线 · 点击下线":"点击发布"}</span></button></form><form action={enAction}><button className={en?.isPublished?"is-live":""}><b>English</b><span>{en?.isPublished?"Live · Unpublish":"Publish"}</span></button></form><ConfirmForm action={remove} message="确定删除这个案例？删除后将移入归档。"><button className="delete-content"><b>删除</b><span>移入归档</span></button></ConfirmForm></div>; const localeState=(t:typeof zh,label:string)=>{if(!t)return <span className="locale-missing">{label}：未填写</span>;return t.isPublished?<span className="locale-live">{label}：已发布</span>:<span className="locale-draft">{label}：未发布</span>}; const banner=<div className="locale-banner">{localeState(zh,"中文")}<em>·</em>{localeState(en,"English")}<em>·</em><span>未填写语言的案例仅对内可见，海外客户看不到。</span></div>; return <AdminPage title={`编辑 · ${zh?.title??item.slug}`} eyebrow="PROJECT EDITOR" tenant={session.tenant.name} action={actions}>{banner}{(state.saved||state.created)&&<div className="save-notice">案例内容已保存。</div>}{state.error&&<div className="form-error">{state.error==="duplicate"?"该 URL 别名已存在，请更换后再试。":"请检查必填项和 URL 格式。"}</div>}<ProjectForm action={update} submitLabel="保存修改" products={products.map((p) => ({ id: p.id, label: `${p.model} · ${p.translations[0]?.name ?? ""}` }))} value={{slug:item.slug,category:item.category,location:item.location??"",titleZh:zh?.title??"",titleEn:en?.title??"",descriptionZh:zh?.description??"",descriptionEn:en?.description??"",productIds:item.products.map((p) => p.productId)}}/></AdminPage> }
